### ISSUE TITLE
links im footer sind falsch

### ISSUE THREAD

**Issue by mi5-77** [mi5-77/rl-rechtsanwaelte.de#1]
Es fehlt noch der Markdown-Post Datenschutzerklärung, da bisher unklar war was tatsächlich an Daten beim Besuch der Seite erhoben wird.

**Comment by ibotty** [comment]
Bitte schreibt den Text!

Zu erwähnen:

 * IP-Adresse und Browser-User-Agent wird gespeichert, sonst nichts,
 * externe Inhalte: maps.google.com (wenn eingebunden).

**Comment by mi5-77** [comment]
Soll ich auch die .md-Datei erstellen?

Text wäre nach den jetzigen Kenntnisstand:

title: Datenschutzerklärung
---
Datenschutz nehmen wir sehr ernst, daher erheben wir selbst keine Daten über Ihren Besuch auf unserer Seite. Wir verwenden keine Cookies oder anderen technischen Mittel, die Ihr Nutzungsverhalten erfassen. 

Beim Besuch unserer Seite werden vom Hosting-Anbieter automatisch Ihre IP-Adresse sowie der Browser-User-Agent gespeichert. Der Serverstandort befindet sich in den Niederlanden.

Soweit von unserer Seite auf externe Inhalte verlinkt wird, richtet sich - im Falle Ihres Besuch der externen Seite - die Erhebung Ihrer Daten nach den jeweiligen Datenschutzerklärungen der externen Anbieter.

**Comment by ibotty** [comment]
Da sollte noch der Google-Maps fall rein. Formulierungsentwurf:

Es werden keine Inhalte Externer ohne Ihre Einwilligung eingebunden. Sollten sie die verlinkte Google-Karte benutzen wollen, werden Daten von Google inc gespeichert. Darauf haben wir keinen Einfluss.
