### ISSUE TITLE
Änderungen werden nicht übernommen

### ISSUE THREAD

**Issue by mi5-77** [mi5-77/rl-rechtsanwaelte.de#10]
Haben heute die Kanzleibeschreibung neu verfasst und die DS-Erklärung korrigiert. Github hat die Änderungen korrekt angezeigt, jedoch sind diese in unseren Browsern weder auf Chrome noch auf Thunderbird zu sehen. Da ist immer noch alles beim alten. ???

**Comment by ibotty** [comment]
obsolete
