### ISSUE TITLE
Über uns

### ISSUE THREAD

**Issue by mi5-77** [mi5-77/rl-rechtsanwaelte.de#2]
Wenn im Menü "Über uns" angeklickt wird, sollen beide posts ("Die Kanzlei" und "Rechtsanwälte) untereinander wie in einem Blog angezeigt werden. Wird auf Kanzlei geklickt, soll die Seite zum post Kanzlei springen bzw. bei RechtsanwäLte* zu RechtsanwäLte*.

Beim Post RechtsanwäLte* fehlen noch unsere Namen ist mir aufgefallen und die Abstände von den Fotos zum Text sind häßlich.

**Comment by ibotty** [comment]
Re "Die Kanzlei" und "Rechtsanwältinnen" untereinander: Das ist schlecht für die  SEO (search engine optimization). Inhalte sollten möglichst nie unter zwei URLLs gleichzeitig verfügbar sein.

**Comment by mi5-77** [comment]
Ok. Wir machen was du sagst: Das "Über uns"-Obermenü kommt weg, stattdessen machen wir dann zwei Menüpunkte, die oben mit auf die Menüleiste kommen, also ohne die zwei Submenüpunkte. Wie auch immer SEO funzt...

**Comment by mi5-77** [comment]
Ach so, der Search-Menübutton mit der hässlichen Lupe soll raus. Wusste leider nicht wo der implementiert ist. Vermute irgendwo im template folder.
