### ISSUE TITLE
Google Maps-Integration

### ISSUE THREAD

**Issue by mi5-77** [mi5-77/rl-rechtsanwaelte.de#3]
Die embedded Map funzt nicht! Warum? :(

**Comment by ibotty** [comment]
Fehlende API-Keys. Ich sehe vier Möglichkeiten:
 * API-Keys holen,
 * Openstreetmap benutzen,
 * keine Karte,
 * statische Karte einbetten (rechtliche Lage klären).

Ich würde empfehlen (Paranoiker-Modus), dass, wenn ihr eine dynamische Karte haben wollt, diese erst nach zusätzlichem Klick geladen wird. Das heißt, es erscheint ein Fenster auf dem nochmals geklickt werden muss, damit die Karte sichtbar wird (analog dem [youtube-fenster auf duckduckgo](https://duckduckgo.com/?q=rick+roll&ia=videos&iax=1&iai=eBGIQ7ZuuiU)).

Was wollt ihr?

**Comment by mi5-77** [comment]
Also wir präferieren die Paranoiker-Variante. Falls es zu kompliziert ist, die Openstreetmap-Variante .
Muss bei der verwendeten Variante noch was in der Datenschutzerklärung ergänzt werden? Es werden doch dann auf unserer Seite keine Daten gesammelt... Oder?

**Comment by ibotty** [comment]
Lest Euch mal folgendes durch, ob das für euch akzeptabel ist
 https://developers.google.com/maps/documentation/javascript/usage

Wenn ja, besorge ich euch den API-Key und binde es ein.

**Comment by mi5-77** [comment]
Die Lizenzbedingungen sind so semi-prickelnd. Ich verstehe nicht wirklich, was ich mir unter einem map load vorstellen soll. Kann es passieren, dass bei einem Ereignis, wie etwa einem Angriff auf die Seite die 25.000 Zugriffe pro Tag überschritten werden? Ein anderes Beispiel wäre etwa, wenn wir in einem öffentlichkeitswirksamen Fall vertreten und es gibt an einem Tag etwa 100.000 Zugriffe auf die Seite, die sich auch alle ansehen wollen, wo wir unsere Kanzlei haben. Da hört sich für mich 25.000 map loads nicht nach viel an. Ansonsten können wir froh sein, wenn sich überhaupt Leute auf unsere Seite verirren.
Ha, und du wirst der erste sein!

**Comment by ibotty** [comment]
Bots werden wahrscheinlich nicht Google Maps laden. Aber sicher ist man da nie. Irgendeine Nutzungsbeschränkung gibt es immer. Das geht gar nicht anders. Openstreetmap hat bestimmt auch so was. Wenn sich was abzeichnet, dann kann man immer noch zu premium-Paketen greifen... Wenn wir den klick-to-invade-privacy-button haben, werden sich die wenigsten die map laden. Your choice.

**Comment by mi5-77** [comment]
Ah ok. Go!

**Comment by ibotty** [comment]
und: noch eine tos zum durchnicken ;)

https://developers.google.com/maps/terms

**Comment by mi5-77** [comment]
Schau mal bitte hier unter "Google Maps Embed API". Das ist unter "Unlimited free usage."
https://developers.google.com/maps/pricing-and-plans/#details
Ansonsten bleibt es beim alten. Zu den terms gebe ich nachher bescheid.

**Comment by mi5-77** [comment]
Falls es mit der embed free API nicht klappt, trotzdem ok.

**Comment by ibotty** [comment]
Es muss nun **nur** noch schön werden. Toll wäre ein Screenshot von Google Maps (der leicht ausgegraut wird) als Hintergrund für die Warnmitteilung. Geht das rechtlich?

**Comment by mi5-77** [comment]
Ne, für einen Screenshot wäre dann wohl ein Google Static Maps API erforderlich. Jedenfalls ist ein Screenshot ohne Lizenz eine Urheberrechtsverletzung. Wir werden das aber viel toller machen und uns selbst eine Karte zeichnen für den Hintergrund. Bekommst du nächste Woche zugeschickt.
Irgendwelche Präferenzen bei Größe + dpi?

**Comment by ibotty** [comment]
So gut, wie nur möglich. Momentan ist der frame 600x400 px groß, aber ich kann das immer noch skalieren, also malt ruhig schön und scannt großformatig.

**Comment by ibotty** [comment]
Und?

**Comment by mi5-77** [comment]
Oki. Sorry für die lange Bearbeitungszeit, aber alle Entwürfe bisher waren Schrott. Jetzt habe ich mal kurzerhand den Kopierer angeschmissen, et voilà! Mail kommt gleich.

**Comment by mi5-77** [comment]
Wie embedde ich denn eigentlich die erstellte Karte in den grauen Kasten? Habe im Netz leider keine Lösung gefunden, daher muss ich fragen.

**Comment by ibotty** [comment]
Oho, my bad. Ich kümmere mich heute oder morgen drum.

**Comment by mi5-77** [comment]
Keinen Stress bitte! Ich könnte es ja auch machen - wenn ich wüsste wie...
Wahrscheinlich dauert aber Erklären länger, als es selber machen. :( Daher wie du magst.

**Comment by ibotty** [comment]
Ich hab das jetzt mal endlich gemacht. Guckt mal rauf und sagt, ob da noch was verändert werden soll?
