### ISSUE TITLE
schönere URLs

### ISSUE THREAD

**Issue by ibotty** [mi5-77/rl-rechtsanwaelte.de#6]
Ich persönlich mag URLs wie `rl-rechtsanwaelte.de/impress/impressum/` oder `rl-rechtsanwaelte.de/kont/kontakt/` nicht so gern. Sollten sie nicht einfach `rl-rechtsawaelte.de/impressum/` heißen?

**Comment by mi5-77** [comment]
Stimmt! Der hat die Zusatzordner beim "jekyll build" erstellt mit den jeweiligen index.html-Dateien. Wusste nicht, wie man die .md-Dateien im Mainfolder den jeweiligen Links zuordnet. Feel free!
