### ISSUE TITLE
mobilmenu ist hässlich

### ISSUE THREAD

**Issue by ibotty** [mi5-77/rl-rechtsanwaelte.de#7]
.. und hat komische mobil links. Ich schlage vor, die Titel der seiten zu verkürzen "Kanzlei", Wir", " Wo" oder so, dann klappt das auch ohne extra-Menü. Na?

**Comment by mi5-77** [comment]
Wie hässlich?! Muss ich mir zu Hause ansehen, da ich hier auf dem Thinkpad die Seite nicht local hosten kann. Habe mich bisher nicht getraut die ExecutionPolicy in der Powershell auf dem Arbeitsrechner zu ändern. Also kein Chocolatey, kein Ruby, kein Jekyll... 
Ansonsten wat denn für ein mobil link. Du meinst das "Burgermenü" auf der linken Seite? Wenn Kanzlei reinpasst, müsste doch der Rest auch gehen. Gibt es eine Zeichenbegrenzung und welche Titel betrifft das deiner Meinung nach?
Verkürzung wird ansonsten schwierig. Sei froh dass wir keinen Titel "Anfechtungsfortsetzungsfeststellungsklage" haben. :/

**Comment by ibotty** [comment]
Guck doch auf rl-rechtsanwaelte.de

**Comment by mi5-77** [comment]
Das einzige issue das ich dort sehe, ist die häßliche social media bar, unten mit dem search button. Ansonsten finde übertrifft die Seite meine Erwartungen um ein vielfaches. :*
Ich weiß nicht, was du daran doof findest. Alles gut.
