### ISSUE TITLE
Datenschutz + Impressum

### ISSUE THREAD

**Issue by mi5-77** [mi5-77/rl-rechtsanwaelte.de#8]
Der erste Absatz ist in größeren Fonts, obwohl dieser in der .md-Datei als normaler Textcontent eingefügt ist.

**Comment by ibotty** [comment]
Kannst du nochmal nachgucken? Bei mir mit Firefox und android Firefox seh ich das Problem nicht.

**Comment by mi5-77** [comment]
Ja, bei Firefox, Chrome, Edge und Safari, auch auf mehreren Rechnern. Mobile Versionen sind nicht betroffen. Ich schicke Screenshots per Mail. Wenn ich hier dazu komme...

**Comment by ibotty** [comment]
Fixed. War nur bei großem Fenster sichtbar.
