### ISSUE TITLE
Google maps brauch die places-id

### ISSUE THREAD

**Issue by ibotty** [mi5-77/rl-rechtsanwaelte.de#9]
Die gibt es anscheinend noch nicht. Prinzipiell mit Suchterm "RL RechtsanwäLte*" zu finden unter
 https://developers.google.com/places/place-id#find-id

**Comment by mi5-77** [comment]
Ok. Für RL RechtsanwäLte* habe ich gestern auf business.google.com schon was angemeldet, allerdings wird der Freischaltcode erst nächste Woche per Post zugeschickt. Den muss ich dann noch eingeben, dann sollte es gehen. Danke für den Link für Rechtsanwälte. Wir werden die Tage noch weitere Places für D. und mich anlegen. Melden uns dann wenn alles durch ist.

**Comment by mi5-77** [comment]
Der Maps-Eintrag für RL ist durch, aber immer noch keine Place-ID. Habe schon gegoogelt, aber keinen Plan woran das liegen mag.

**Comment by ibotty** [comment]
Yeah. Places id ist ChIJ43HCqF9OqEcRrIXUNqEA7pg

**Comment by ibotty** [comment]
Btw: Ihr taucht persönlich noch nicht bei Google maps auf. Das sollte man irgendwann mal überprüfen.
